package model.enums.elements;

public enum MarkerType {
    CARPENTER_MARKER,
    COOK_MARKER,
    EXPLORER_MARKER,
    SOLDIER_MARKER,
    FRIDAY_MARKER,
    DOG_HELPER_MARKER,
    HUNTER_HELPER_MARKER,
    BUILDER_HELPER_MARKER,
    COLLECTOR_HELPER_MARKER,
    EXPLORER_HELPER_MARKER,
    ROUND_MARKER,
    WOUND_MARKER,
    BLACK_MARKER,
    WHITE_MARKER,
    BLUE_MARKER,
    WOOD_MARKER,
    FOOD_MARKER,
    LONG_EXPIRY_DATE_FOOD_MARKER,
    FUR_MARKER
}
