package model.enums.elements;

public enum MarkerType {
    CARPENTER_MARKER,
    COOK_MARKER,
    EXPLORER_MARKER,
    SOLDIER_MARKER,
    FRIDAY_MARKER,
    DOG_MARKER,
    HUNTER_EXTRA_MARKER,
    BUILDER_EXTRA_MARKER,
    COLLECTOR_EXTRA_MARKER,
    EXPLORER_EXTRA_MARKER,
    ROUND_MARKER,
    WOUND_MARKER,
    BLACK_MARKER,
    WHITE_MARKER,
    BLUE_MARKER,
    WOOD_MARKER,
    FOOD_MARKER,
    LONG_EXPIRY_DATE_FOOD_MARKER,
    HIDE_MARKER
}
