package model.enums.elements;

public enum TokenType {
    FIRST_PLAYER_TOKEN,
    ADVENTURE_TOKEN,
    DISCOVERY_TOKEN,
    RAIN_CLOUD_TOKEN,
    SNOW_CLOUD_TOKEN,
    CAMP_TOKEN,
    SHELTER_TOKEN,
    DETERMINATION_TOKEN,
    SHORTCUT_TOKEN,
    STORM_TOKEN,
    BASKET_TOKEN,
    SACK_TOKEN,
    BROWN_WOUND_TOKEN,
    GRAY_WOUND_TOKEN,
    GREEN_WOUND_TOKEN,
    ONE_MORE_WOOD_TOKEN,
    ONE_MORE_FOOD_TOKEN,
    ONE_MORE_CHARACTER_MARKER_TOKEN,
    ROLL_AGAIN_IF_SUCCESS_TOKEN,
    BEAST_STRENGTH_PLUS_ONE_TOKEN
}
